# Generated by Django 2.0.1 on 2018-10-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0002_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=50),
        ),
    ]
