# Generated by Django 2.0.1 on 2018-10-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0004_auto_20181025_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='arguement',
            new_name='argument',
        ),
    ]
