# Generated by Django 2.0.1 on 2018-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0004_auto_20181025_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='argument',
            old_name='last_date',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='lobby',
            old_name='arguement',
            new_name='argument',
        ),
    ]
