# Generated by Django 2.0.1 on 2018-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0005_auto_20181030_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argument',
            old_name='topic_name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='argument',
            name='argument_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
