# Generated by Django 2.0.1 on 2018-11-02 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0007_auto_20181101_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argue_app.Status'),
        ),
    ]
