# Generated by Django 2.0.1 on 2018-11-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0009_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
