# Generated by Django 2.0.1 on 2018-12-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argue_app', '0010_auto_20181101_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='forfeited',
            field=models.ManyToManyField(related_name='forfeited', to='argue_app.Profile'),
        ),
    ]
